name: My Subgraph 16
slug: my-subgraph-16
apiKey: 9542fdeec244b51444ab31f4222f29cf9024d7334821e563cef4761b6bd785d4
region: us-east-1
resource:
  schema: ./schema.graphql
  handler: ./handler.ts
dataSources:
  - chainId: 2484
    contractAddress: "0x7C0203773f98bDDfAF0920a050fDd3B4cAc57eD4"
    startBlock: 14000
  - chainId: 39
    contractAddress: "0x7C0203773f98bDDfAF0920a050fDd3B4cAc57eD4"
    startBlock: 14000
eventHandlers:
    - event: PostCreated(indexed address,string)
      handler: handlePostCreated
    - event: UserRegistered(indexed address,string)
      handler: handleUserRegistered
